### ISSUE TITLE
Lab: Declarative Policy Definition in CSV Files

### ISSUE THREAD

**Issue by mcombi** [RedHatQuickCourses/devhub-admin#10]
https://redhatquickcourses.github.io/devhub-admin/devhub-admin/1/chapter2/rbac.html#_lab_declarative_policy_definition_in_csv_files 
In section 7, the API Import doesn't work as expected. Can this be related to some errors in the previous configuration?
![image](https://github.com/RedHatQuickCourses/devhub-admin/assets/100132715/823918fe-12d6-4be0-8973-e6ff101ebb5a)

**Comment by rsriniva** [comment]
it's possible. please see the two WARNINGs mentioned at the bottom of this exercise and check if you have mis-configured. You can temporarily disable RBAC and experiment. Unfortunately, RBAC is not well documented. v1.1 introduces a new web UI for RBAC, that should hopefully make it easier

**Comment by mcombi** [comment]
Hi @rsriniva , was definetly some typo or some problem with the indentation of cm. 
Thanks
