### ISSUE TITLE
[Request] Update the lab to use the RHDH Operator

### ISSUE THREAD

**Issue by LiorHaim** [RedHatQuickCourses/devhub-admin#11]
Hi,

First of all - thank you for the great course. We've been using it for a while now and it's great!

Is there any chance you'll update the course soon to use the Operator to install the instance and configure it later on?
It could have a real major help and impact for our training.

Thanks alot!

**Comment by rsriniva** [comment]
Shalom! Thank you for your kind comments. Immediately after releasing the material, RHDH 1.1 came out with the operator going GA. Will discuss with my manager and let you know when we can write a new section for operator. We are now busy with lots of AI material:-)

**Comment by LiorHaim** [comment]
Thanks @rsriniva !
The lab is extremely helpful and actually helped us a lot on 2 deals we made :)

Let me know if there's any way we can try and help pushing towards keeping this lab up to date as much as possible.

**Comment by rsriniva** [comment]
Thanks for your kind comments @LiorHaim . I will update the course to 1.2 GA starting this week. Let's hope the GA does not slip ;-)

**Comment by LiorHaim** [comment]
@rsriniva haha sure hope it won't.
Thanks once again!
