### ISSUE TITLE
inconsistency of secret CR name between "Basic Configuration" sub sections

### ISSUE THREAD

**Issue by bugbiteme** [RedHatQuickCourses/devhub-admin#14]
In the `Basic Configuration->Basic Configuration` section, it is instructed to create a secret called `secrets-rhdh` but the screenshot shows it being named `rhdh-secrets`

Later in `Basic Configuration-> GitHub Integration and Authentication`, there is a reference to an existing `rhdh-secrets`

This is confusing and makes it hard to troubleshoot if issues come up

**Comment by rsriniva** [comment]
good catch! fixed in main. Thank you for reporting this @bugbiteme !
