### ISSUE TITLE
Please provide completed yaml in "GitHub Integration and Authentication" section

### ISSUE THREAD

**Issue by bugbiteme** [RedHatQuickCourses/devhub-admin#15]
While building on the ConfigMap CR in `GitHub Integration and Authentication`, can you please provide a link to a completed yaml of `app-config-rhdh` that can be edited and applied? Breaking it into sections is good, but seeing what it should ultimately look like would be very helpful.

**Comment by rsriniva** [comment]
fixed in main. Added config at end of section. Thank you for suggesting this @bugbiteme !
