### ISSUE TITLE
Basic Configuration instructions assumes Operator is used to setup Developer Hub

### ISSUE THREAD

**Issue by bilal-rh** [RedHatQuickCourses/devhub-admin#17]
Basic Configuration -> GitHub Integration and Authentication (https://redhatquickcourses.github.io/devhub-admin/devhub-admin/1/chapter2/git-auth.html)
Installation part has different ways to install developer hub such as helm, cli, operator. After install, the Basic Configuration instructions assume that the developer operator is used for installation and confuse the individual that has used helm charts for installation.
Please keep all the instructions generic considering individuals can follow helm, cli or operator to install and the subsequent sections after install should have instructions for all possible ways.

**Comment by rsriniva** [comment]
This is slightly tricky to cover both options for every hands-on. The process to edit app-config is slightly different for helm charts. I will try and point out how to edit it once. I am making an assumption here that operator would be the preferred option for the majority of admins maintaining the RHDH instance.
