### ISSUE TITLE
Update docs: OpenShift 4.13 Single Node Cluster deprecated

### ISSUE THREAD

**Issue by sgahlot** [RedHatQuickCourses/devhub-admin#8]
While following the _RHDH administration_ course, the prerequisite 1 points to ordering [OpenShift 4.13 Single Node Cluster](https://demo.redhat.com/catalog?item=babylon-catalog-prod/openshift-cnv.ocp413-single-node-cnv.prod&utm_source=webapp&utm_medium=share-link) but this option is deprecated. It is instead pointing to the alternative [OpenShift Single Node Cluster](https://demo.redhat.com/catalog?search=single&item=babylon-catalog-prod%2Fopenshift-cnv.ocpmulti-single-node-cnv.prod).

**Comment by rsriniva** [comment]
Thanks for opening an issue @sgahlot. This is now fixed in main. Added link to new catalog item
