### ISSUE TITLE
Update docs: Install the RHDH Helm Chart - step 4

### ISSUE THREAD

**Issue by sgahlot** [RedHatQuickCourses/devhub-admin#9]
In step 4 of **Install the RHDH Helm Chart** (_Red Hat Developer Hub Administration_ course), update the instructions to refer to `dynamic.redhatworkshops.io` instead of `dynamic.opentlc.com`.

**Comment by rsriniva** [comment]
thanks for reporting this @sgahlot ! fixed in main
